apiVersion: v1
kind: Service
metadata:
  labels: {{ include "db.common.labels" . | nindent 4}}
  name: {{ .Values.db_name }}
spec:
  selector: {{ include "db.common.labels" . | nindent 4}}
  ports:
    - name: "5432"
      port: {{ .Values.db_port }}
      targetPort: {{ .Values.db_port }}
