apiVersion: v1
# Secret to store sensitive data (username, password,...)
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: {{ .Values.db_username }}
  password: {{ .Values.db_password }}
