apiVersion: v1
kind: Service
metadata:
  labels: {{ include "server.common.labels" . | nindent 4}}
  name: {{ .Values.server_name }}
spec:
  selector: {{ include "server.common.labels" . | nindent 4}}
  ports:
    - name: "8080"
      port: {{ .Values.server_port }}
      targetPort: {{ .Values.server_port }}
  type: LoadBalancer
