apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.network/springreactive_my-network: "true"
        io.kompose.service: db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - log_statement=all
          env:
            - name: POSTGRES_DB
              value: test_reactive
            - name: POSTGRES_PASSWORD
              valueFrom:
                # Getter value form `secret`
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                # Getter value form `secret`
                secretKeyRef:
                  name: db-secret
                  key: username
          image: postgres:10.5
          name: db
          ports:
            - containerPort: 5432
      restartPolicy: Always
