apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      labels:
        io.kompose.network/springreactive_my-network: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: SPRING_R2DBC_URL
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: db_connection_string
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                # Getter value form `secret`
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                # Getter value form `secret`
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: application_port
          image: dactien020796/spring-reactive-sample
          name: application-server
          ports:
            - containerPort: 8080
      restartPolicy: Always
