apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: server
  name: server
spec:
  selector:
    io.kompose.service: server
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
